module.exports = {
  sidebar: {
    Basic: ['basic/introduction', 'basic/CR_template'],
    button: ['button/Button', 'button/ButtonLink'],
    card: [],
    charts: [
      'charts/cartesian/XAxis',
      'charts/cartesian/YAxis',
      'charts/cartesian/CartesianGrid',
      'charts/BarGauge',
      'charts/LineChart',
      'charts/PieChart',
      'charts/RadarChart',
      'charts/SankeyChart',
      'charts/TreeMap',
    ],
    common: [],
    form: [],
    layout: [],
    list: ['list/CheckBox', 'list/CheckList', 'list/Item', 'list/RadioList'],
    modal: [],
    pagination: [],
    paper: [],
    table: [],
    Toast: [],
    tooltip: [],
  },
};
